version: '2'

services: 
  bbps:
    build: .
    image: github.com/shintech/backbone_postgres_seed:1.2.2
    container_name: bbps
    env_file:
      - ./bbps.env
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./data